### PR TITLE
Adding measures from BldgSync-Gem / refactoring of parametric schedule measure

### PR DESCRIPTION
**Pull request by TMaile**

### CODE REVIEW

**Comment by nllong** [comment]
@TMaile - do we still need to merge this down?

**Comment by TMaile** [comment]
@nllong this branch contains the refactored code for the parametric schedules, the os_lib_model_generation_bricr.rb file and quite a number of measures that we use in BldgSync (inherited from BRICR). If we want/need this then yes.

**Comment by nllong** [comment]
Okay, I'll loop in @DavidGoldwasser to see where we want to put these. I think that we will want these to go into an EE openstudio extension. Thanks for chiming in.

**Comment by nllong** [comment]
@DavidGoldwasser can we get this merged down ASAP. We are trying to merge down BuildingSync gem and this is needed.

**Comment by nllong** [comment]
no longer valid

**Pull request closed without merging**
