### PR TITLE
Bcl stage updates

### PR DESCRIPTION
**Pull request by DavidGoldwasser**
@nllong and @kflemin 

I renamed any files under tests directory that start with test and updated XML's and other references to those files before trying to stage and push to BCL. Everything that was put in the `staged/update` directory was uploaded using rake push, but everything in `staged/push` failed to post with rake task. All but one of them successfully uploaded using web interface with one exception. `create_parametric_schedules` shows waiting for approval, but I don't see in it group content.

Screen Shot 2020-06-23 at 9 45 31 PM

One last thing. For some reason `create_DOE_prototype_building` shows up in `push` instead of `update` even though it is already on BCL with matching UUID. After manually updating the measure instead, and re-staging, it still showed as 'push`. Not sure of the cause

### CODE REVIEW

**Comment by DavidGoldwasser** [comment]
This branch was made from the rake_update branch which is open as another pull request.

**Comment by nllong** [comment]
@DavidGoldwasser -- looks like the tests are failing. Is this still good to merge?

**Comment by DavidGoldwasser** [comment]
@nllong One in 15 tests in SetWindowToWallRatioByFacade failed, I'm almost certain because of intersection, as it is test with door, that probably splits walls before adding windows. This measure wasn't touched here.Do I just keep kicking of CI again until it passes.

```Failure: test_door_nothing(Minitest::Result) [/home/ubuntu/jenkins/workspace/dio-model-articulation-gem_PR-29/openstudio_3_x/lib/measures/SetWindowToWallRatioByFacade/tests/SetWindowToWallRatioByFacade_Test.rb:601]: Expected false to be truthy.```

**Comment by nllong** [comment]
Oh man. Non determistic CI is a major problem. Why would kicking off another CI run cause things to pass all of a sudden? Which part of the model generation is non-deterministic?

**Comment by DavidGoldwasser** [comment]
@nllong 
Non-Deterministic items
- when intersection crashes seems non-deterministic, and also platform specific. 
- Need to write test but believe based on input from @kflemin that asking for OpenStudio model objects like surfaces etc. is non-deterministic now. Not sure if this is new to 3.0. Cat has been helping to update ruby code in openstudio-extension_gem to sort any model objects before using them, but this may extend to openstudio-standards as well. Or just other measures that don't always sort objects when the order shouldn't matter.

**Comment by DavidGoldwasser** [comment]
@nllong Looks like the second attempt worked :) I know we still have to address this, I'll try to file an OS issue this weekend if I can setup script to show it.

**Pull request merged**
