### PR TITLE
add empd material properties measure

### PR DESCRIPTION
**Pull request by GFlechas**
addresses issue #72. New measure to add empd material properties to an OpenStudio model.

### CODE REVIEW

**Comment by DavidGoldwasser** [comment]
@GFlechas, Just wanted to check if you have sent in a code contribution email yet for this repository.  If not this week we can try to review and merge this in next week.

**Review by nllong — CHANGES_REQUESTED** [review]
Thanks @GFlechas for this measure. Can you run code cleanup on your PR? Just do the following on your local checkout:

```
cd lib/measures/add_empd_material_properties
bundle exec rake openstudio:rubocop:auto_correct
bundle exec rake openstudio:update_measures
```

Only commit the files that change in your `add_empd_material_properties` measure directory. 

Also, don't forget to submit the contribution agreement.

Thanks again for contributing to OpenStudio!

**Comment by GFlechas** [comment]
I think everything is good. I have run code cleanup on my PR. I'm a git novice so if I've made a mistake please let me know and I'll get it fixed!

I will get the contribution agreement submitted shortly.

Thank you!

**Review by DavidGoldwasser — APPROVED** [review]
other measure XML changes may create merge conflict

**Comment by DavidGoldwasser** [comment]
@GFlechas the variable names were changed in the measure.rb but not in the test. You can change these here, then update the meaxure.xml again and should be ready. 
https://github.com/GFlechas/openstudio-model-articulation-gem/blob/develop/lib/measures/add_empd_material_properties/tests/add_empd_material_properties_test.rb#L83-L92

I tried to do it myself, but my attempt broke something in our CI, maybe we will have better luck if it is fixed in your fork and on PR #73.
https://github.com/NREL/openstudio-model-articulation-gem/pull/81

David

**Comment by DavidGoldwasser** [comment]
The CI on other branch worked now which closed this PR.

**Pull request merged**
