### PR TITLE
Prototype building models for 90.1-2016

### PR DESCRIPTION
**Pull request by lymereJ**
Add ASHRAE Std. 90.1-2016 as a possible argument for the create DOE prototype building model measure.

### CODE REVIEW

**Comment by DavidGoldwasser** [comment]
This is passing, but there is no test in it for 2016 yet

**Comment by lymereJ** [comment]
I just added 90.1-2016 to the school tests. Please, let me know if you need a totally new test.

**Comment by lymereJ** [comment]
@DavidGoldwasser - I see that the tests have failed. I don't have access to the failure report. Could it be because it the previous version of `openstudio-standards` is used (as opposed to the upcoming one that does include `90.1-2016`)?

**Comment by DavidGoldwasser** [comment]
@lymereJ the errors in this test are related to some geometry updates and are impacting the create_bar measures, not the measures you llisted in this PR but still part of the test
https://github.com/NREL/openstudio-model-articulation-gem/pull/66 

Once we decide how we want to resolve that, this could be merged, but we still need to run update `openstudio measure -u create_DOE_prototype_builidng` so that the measure.xml for this measure gets updated.

CC: @tijcolem @mdahlhausen

**Comment by lymereJ** [comment]
Sounds good, thanks! I've updated the XML file.

**Comment by DavidGoldwasser** [comment]
@lymereJ do we want to update DOE baseline measure for 2016 as well?

**Comment by lymereJ** [comment]
@DavidGoldwasser not for the moment, it's still under development under its own branch, the implementation is based on 90.1-2019, not 2016, although the requirements are very similar.

CC: @dmaddoxwhite.

**Pull request merged**
