### PR TITLE
Bonnema/add

### PR DESCRIPTION
**Pull request by bonnema**

### CODE REVIEW

**Comment by DavidGoldwasser** [comment]
I'm running locally in 2.9.1. I did notice some measures that we had updated to require 2.9.0 don't reflect that on the XML's here. These are due to changes in methods in standards gem. I may have updated these after they were pulled to new repo. I have about 10 commits to move over, I can update this at the same time by comparing CI html page that.
https://github.com/NREL/OpenStudio-measures/blob/develop/nrel_published/create_bar_from_building_type_ratios/measure.xml#L1594

**Comment by DavidGoldwasser** [comment]
This did run on my machine (2.9.1), when I updated measures from old repo, all the failed measure tests were resolved. Still having issues getting CI to run.

**Comment by DavidGoldwasser** [comment]
@nllong and @tijcolem I don't fully understand the role of the `spec` directory in the CI, but the failure seems to be related to it trying to run this OSW, which contains a measure that requires 2.9.0 or later, with 2.8.1
https://github.com/NREL/openstudio-model-articulation-gem/blob/develop/spec/openstudio/model_articulation_spec.rb#L81

It isn't a surprise that this is failing, but it is preventing the CI on the measures from running.

**Comment by DavidGoldwasser** [comment]
@nllong have you had a chance to try to update this CI to use 2.9.1

**Comment by nllong** [comment]
@tijcolem -- can you update this branch to use OpenStudio 2.9.1?

**Comment by DavidGoldwasser** [comment]
@nllong dashboard from list last run is not rendering, so I can't confirm if any errors in 2.9.1
https://ext-gem-dashboard.s3.amazonaws.com/openstudio-model-articulation-gem/PR-11/16/develop/dashboard/index.html

But I'm past the OSW test issues I had been seeing. Any thoughts on why the dashboard and link above doesn't work?

**Comment by tijcolem** [comment]
@DavidGoldwasser it looks like it uploaded the result files to s3 but perhaps there is a missing file related for the dashboard. You can see it uploaded starting here: https://ci.commercialbuildings.dev/blue/organizations/jenkins/openstudio-model-articulation-gem/detail/PR-11/16/pipeline/#step-35-log-1

**Comment by tijcolem** [comment]
Link https://ext-gem-dashboard.s3.amazonaws.com/openstudio-model-articulation-gem/PR-11/16/develop/dashboard/index.html is working now. 

The dashboard dir was in the wrong place on s3 `/develop/test_results/dashboard` vs the expected `develop/dashboard/index.html`. Not sure what has changed this to change.

**Comment by DavidGoldwasser** [comment]
Thanks @tijcolem. @nllong it looks good for 2.9.1 (see below) can we merge it in :)

Screen Shot 2020-02-28 at 5 44 36 PM

**Pull request merged**
