### PR TITLE
Testing on OpenStudio 3.2.0-alpha

### PR DESCRIPTION
**Pull request by tijcolem**
PR to start testing measures on 3.2.0-alpha SDK.

### CODE REVIEW

**Comment by DavidGoldwasser** [comment]
@tijcolem run bundler tests passed but there were 2 measures with 3 failures each test measures with openstudio...

**Comment by tijcolem** [comment]
@DavidGoldwasser Yep, bundler tests pass with updated version of ext gem as it's pulling from develop.  Once we have new release of that we'll get an update ext gem 0.4.1 and this should pass. 

https://ci.commercialbuildings.dev/blue/organizations/jenkins/openstudio-model-articulation-gem/detail/PR-66/1/pipeline/22

**Comment by tijcolem** [comment]
@DavidGoldwasser So I'm looking at the latest CI run which is using 3.2.0-alpha+412729e894 and seem to have resolved 5/6 of the previous failures but are now getting new failures for CreateBarFromDOEBuildingTypeRatios. 

It looks geometry related. Example of failure results for dual_bar_1

```
**ERROR MESSAGES**
PrimarySchool Corridor doesn't have the expected floor area (actual 15,728 ft^2, target 16,330 ft^2)
Sum of actual floor area is 99398.20066022337 ft^2, sum of target floor area is 100000.0.
```

3.2.0-alpha+412729e894 has the geometry related changes.  It seems likely the reason. Do these tests need to be updated to reflect update geo calcs, or is something off in OpenStudio?

**Comment by DavidGoldwasser** [comment]
Since I've added 2016 and 2019 to ext gem I should update measure.xml for new arguments that will show up. I'll have to have local installer to do that. If not that can wait until future update.

**Review by nllong — APPROVED** [review]
sweeet!

**Pull request merged**
