### PR TITLE
Test 3.3.0 rc2

### PR DESCRIPTION
**Pull request by tijcolem**
DO NOT MERGE.

Testing using 3.3.0-rc2

### CODE REVIEW

**Comment by DavidGoldwasser** [comment]
@tijcolem I assume the do not merge can be ignored on this now. @nllong assuming tests pass it should be all set to make 0.5.0 release of model articulation gem.

**Comment by tijcolem** [comment]
@DavidGoldwasser The Jenkins file on this branch (https://github.com/NREL/openstudio-model-articulation-gem/blob/test_3.3.0-rc2/Jenkinsfile#L3) ) is referencing a RC build branch and I didn't want this to get merged to develop branch. I can switch it back if you have a commit on this that you want merged in.

**Comment by DavidGoldwasser** [comment]
@tijcolem I made other fixes in this branch that aren't somewhere else. I can make a new branch from this and change that, or can make the change here. I'm fine either way. Whatever pattern we use here I'll follow on other measure gem repos.

**Comment by DavidGoldwasser** [comment]
@nllong and @tijcolem here is new branch with reverted jenkins file. I'll use same name on other measure gem repo

**Pull request closed without merging**
