### PR TITLE
Xml updates for 32 and bar and typical documentation update

### PR DESCRIPTION
**Pull request by DavidGoldwasser**

### CODE REVIEW

**Comment by DavidGoldwasser** [comment]
@nllong I will make a release on after setting up webhooks in Github to test BCL2 workflow.

**Comment by DavidGoldwasser** [comment]
@nllong no, I'm surprised something is failing, I'll look into that

**Comment by DavidGoldwasser** [comment]
@tijcolem I'm seeing this error. It isn't measure failing now, system isn't running.

```
mv test test_with_cli_bundler
mv: cannot stat 'test': No such file or directory
```
Not sure what changed since last time. Any ideas?

**Comment by tijcolem** [comment]
@DavidGoldwasser It's failing due to the rubocop issue. See this line here:  (obsolete configuration found in .rubocop-http---s3-amazonaws-com-openstudio-resources-styles-rubocop-v3-yml, please update it) in /srv/jenkins/git/openstudio-model-articulation-gem/PR-77/1/.bundle/install/ruby/2.7.0/gems/rubocop-1.15.0/lib/rubocop/config_obsoletion.rb:43:in `reject_obsolete!'

If you can merge in #74 and then we should re-run this CI job and it should pass, or at least get past this error.

**Comment by DavidGoldwasser** [comment]
@tijcolem I'm still seeing similar error now.

**Comment by DavidGoldwasser** [comment]
@tijcolem any thoughts on why this isn't getting as far as the rubocop branch? I did see issue there maybe is related to changed method name in standards that might have been updated between 3.2.0 and 3.2.1

**Comment by DavidGoldwasser** [comment]
@nllong CI is passing now. Do you want to give this a review. Is is primarily updating documentation on a subset of measures, but there were a few minor changes in a few measure arguments. If you (or I can) make a new release after this is merged BCL 2.0 should pick it up.

**Pull request merged**
