### PR TITLE
Update to use rubocop_v4.yml 

### PR DESCRIPTION
**Pull request by tijcolem**
Update to use rubocop_v4.yml and latest gems

### CODE REVIEW

**Comment by DavidGoldwasser** [comment]
@mdahlhausen did `remove_HVAC` get renamed in 3.2? That seems to be cause of this error and is used here
https://github.com/NREL/openstudio-model-articulation-gem/blob/develop/lib/measures/radiant_slab_with_doas/measure.rb#L223

```undefined method `remove_HVAC' for #<ASHRAE9012013:0x000055975dddba90> /srv/jenkins/git/openstudio-model-articulation-gem/PR-74/3/lib/measures/radiant_slab_with_doas/measure.rb:223:in ```

**Comment by mdahlhausen** [comment]
@DavidGoldwasser yes; I snake_cased all method names.  Should be remove_hvac now

**Comment by DavidGoldwasser** [comment]
@mdahlhausen our CI does dual tests now. One on the last installer (with gems frozen) the other off of develop of all of the gems. The idea to be proactive when things break before an installer is out.

**Review by DavidGoldwasser — APPROVED** [review]
I just made a commit I hope will fix the dual CI testing of standards from both 3.2.1 and develop

**Comment by DavidGoldwasser** [comment]
@tijcolem and @nllong Matt D made fix to develop of standards that addressed the CI issue. He made the new dependancies a developer dependancy.

**Pull request merged**
